# Generated by Django 2.1.5 on 2019-05-27 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190526_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('generated_for', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=250)),
                ('requested', models.BooleanField(default=False)),
                ('requests', models.CharField(max_length=100)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.IdData')),
            ],
        ),
        migrations.CreateModel(
            name='RequestPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.BooleanField(default=False)),
                ('date_of_birth', models.BooleanField(default=False)),
                ('race', models.BooleanField(default=False)),
                ('gender', models.BooleanField(default=False)),
                ('nationality', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='references',
            name='permissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.RequestPermissions'),
        ),
    ]
