# Generated by Django 2.1.5 on 2019-05-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_references_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='references',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
