# Generated by Django 2.1.5 on 2019-05-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_references_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpermissions',
            name='check_credit_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestpermissions',
            name='check_criminal_record',
            field=models.BooleanField(default=False),
        ),
    ]
