# Generated by Django 2.1.5 on 2019-05-29 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20190529_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100, null=True)),
                ('card_number', models.CharField(max_length=100, null=True)),
                ('card_expiry_date', models.CharField(blank=True, max_length=100, null=True)),
                ('cvv_number', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
