# Generated by Django 2.1.5 on 2019-05-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_bankingdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='iddata',
            name='photo',
            field=models.ImageField(default=356, upload_to='media/'),
            preserve_default=False,
        ),
    ]
