# Generated by Django 2.1.5 on 2019-05-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_iddata_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iddata',
            name='photo',
        ),
        migrations.AddField(
            model_name='iddata',
            name='bank_letter',
            field=models.FileField(default=5, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iddata',
            name='certified_id',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='certified',
            field=models.BooleanField(default=False),
        ),
    ]
