# Generated by Django 2.1.5 on 2019-05-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20190529_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iddata',
            name='bank_letter',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='iddata',
            name='certified_id_copy',
            field=models.FileField(upload_to='media'),
        ),
    ]
